### ISSUE TITLE
[Enhancement] Compatibility with Perceptive module

### ISSUE THREAD

**Issue by weepingminotaur** [Eligarf/avoid-notice#14]
Would it be possible for this (excellent) module to offer the option to use the Perceptive module for visibility flags and so on, instead of the unlisted Perception module?

**Comment by Eligarf** [comment]
I have found Perceptive far too complex to configure to even get started with it. Saibot393 (its author) has been very gracious in working with me on compatibility with Stealthy, my other module for dnd5e/4e/pf1, but lol, I still haven't a clue about how to actually set Perceptive up to be useful for me in my games. My poor monkey brain was able to grok the Perception module because it has a simple UI, so that is what I used.
I'd like to support Perceptive, but I just can't understand it. If you have pointers to configs or how-tos I'd check them out to see if this was doable

**Comment by Eligarf** [comment]
Support will be in 1.9
